# The name of the channel that the bot should accept messages from
allowed_channel_name = "botfaqs"

# Set the allowed_channel_id variable to the specified value
allowed_channel_id = 1057341784709148884

