# The name of the channel that the bot should accept messages from
allowed_channel_name = "chat2gpt"

# Set the allowed_channel_id variable to the specified value
allowed_channel_id = 1050950698382151680

# The Discord bot token
discord_bot_token = "MTA1MDkwNTIwMDc0NTAwMTAwMQ.G2_5j1.LRlN-wF9LEFktCmtrYChAZxEYErdbRqDWheR1s"
